# Generated by Django 2.1.8 on 2019-05-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('c', 'C Language')], max_length=10)),
                ('code', models.TextField(blank=True)),
            ],
        ),
    ]
