# Generated by Django 2.1.8 on 2019-05-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='code',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'FAIL'), (3, 'WAIT')], default=3),
        ),
    ]
