# Generated by Django 2.2.1 on 2019-05-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190511_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='lang',
            field=models.CharField(choices=[('c', 'C11'), ('cpp', 'C++17'), ('python','python3.7')], max_length=10),
        ),
    ]
