# Generated by Django 2.2.1 on 2019-05-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190517_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='stdin',
            field=models.TextField(blank=True),
        ),
    ]
