# Generated by Django 2.1.7 on 2019-06-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_source_stdin'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
    ]
